DROP TABLE IF EXISTS inventory;
CREATE TABLE inventory (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    code TEXT NOT NULL,
    color TEXT NOT NULL,
    size TEXT NOT NULL,
    qty INTEGER NOT NULL DEFAULT 0
);

DROP TABLE IF EXISTS rentals;
CREATE TABLE rentals (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    code TEXT NOT NULL,
    renter TEXT NOT NULL,
    color TEXT,
    size TEXT,
    qty INTEGER NOT NULL DEFAULT 1,
    date TEXT NOT NULL
);

DROP TABLE IF EXISTS outfits;
CREATE TABLE outfits (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    code TEXT NOT NULL,
    host TEXT NOT NULL,
    size TEXT
);

DROP TABLE IF EXISTS notes;
CREATE TABLE notes (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    code TEXT NOT NULL,
    text TEXT NOT NULL
);

DROP TABLE IF EXISTS supplies;
CREATE TABLE supplies (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    code TEXT NOT NULL,
    text TEXT NOT NULL
);
